### ISSUE TITLE
Creating an AIR for the append-only proof verification

### ISSUE THREAD

**Issue by Jasleen1** [novifinancial/akd#16]
We need to write an AIR that verifies an Append-only proof, so that the client doesn't actually need to receive nodes or rely only an auditor.

**Comment by slawlor** [comment]
Clarification point, what are you referring to with AIR?

**Comment by kevinlewi** [comment]
An AIR stands for Algebraic Intermediate Representation, it is terminology used in zero knowledge proof systems to denote a language for expressing the statement that needs to be proved. It's related to AKD because our initial goals were to use these proof systems to offer a compressed version of the proof that auditors need to audit.

These compressed proofs could be shorter and faster to verify, but require that the server spends the time to compute them. However, I would say it's still TBD on whether or not we can efficiently implement this for AKD, and hence we should regard this as an experimental enhancement that we need to do a bit more research on.

**Comment by kevinlewi** [comment]
We looked into this and decided not to do it due to issues with feasibility. Closing this issue.
